# Generated by Django 6.0.2 on 2026-02-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
